### PR TITLE
Update `time` to fix build failures on rust `1.80.0`

### PR DESCRIPTION
**Pull request by eopb**
Rust `1.80.0` introduced a [new trait implementation](https://github.com/rust-lang/rust/pull/99969) which caused builds of [old versions of the `time` crate to fail](https://github.com/rust-lang/rust/issues/127343).

Since `cargo clone` depends on one of these old `time` versions, builds with rust `1.80.0` or later fail:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

Updating to a version of time with this regression fixed, with `cargo update -p time`, fixes the build of `cargo clone`.

It would also be helpful to get a new release of `cargo clone` after this is merged, since this is also causing the `cargo clone` package to [fail on NixOS](https://github.com/NixOS/nixpkgs/issues/332957#issuecomment-2278578158).

### CODE REVIEW

**Comment by JanLikar** [comment]
Thank you, I appreciate it!

**Review by JanLikar — APPROVED** [review]

**Comment by JanLikar** [comment]
@eopb I released v1.2.3 and created a PR in nixpkgs. See NixOS/nixpkgs#337058. Thanks again for fixing it, I wasn't even aware of the issue. I figured it was just a CI issue.
